os: linux
dist: xenial
language: php

php: 7.4

git:
  depth: 1

install:
  - composer install

before_script:
  - pecl install pcov

jobs:
  include:
    - script: composer phing ci

cache:
  directories:
    - $HOME/.composer/cache
